version: '3.9'

services:
  sample-httpapi:
    image: 1065006561/yydockerhttpapi:v01
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - MySQLConnstr_DefaultConnection=server=mysql-db;user=root;password=123456;database=YY.Sample.Db;SslMode=none;AllowPublicKeyRetrieval=True;
    depends_on:
      - mysql-db
    deploy:
      mode: replicated # global
      replicas: 4
      placement:
        max_replicas_per_node: 3
      restart_policy:
        condition: any # none  # on-failure 
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 50M
          
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.hostname==docker-manager"

  nginx-web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80"
    depends_on:
      - sample-httpapi
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.hostname==docker-manager"